Restricted device UI
ChameleonCloud/blazar-dashboard pull request #20
Opened 2021-07-27 19:54 UTC by Mark-Powers

This adds a gray background to device rows in the calendar that have the "authorized_projects" capability when viewing from a project that does not have authorization to use the device. When hovering over the row, a box appears describing that this device is restricted.

![image](https://user-images.githubusercontent.com/9397092/127218728-b0395a40-297c-4d0e-b05c-ca95a390dcc7.png)

2021-07-27 20:28 UTC, Mark-Powers commented
If a device has the extra capability `restricted_reason`, this is now shown in the tooltip. 

![image](https://user-images.githubusercontent.com/9397092/127222745-6f20a8ff-e5f1-493c-8de5-57cb93fcb7a0.png)

2021-08-02 19:23 UTC, diurnalist requested changes
See if we can collapse this into O(1), if the list of devices grows the calendar will be harder to show over time.

2021-08-02 19:23 UTC, diurnalist commented on blazar_dashboard/content/leases/views.py
> +            full_device = api.client.device_with_capabilities(request, device["id"])
This turns this into an O(N) operation and we pay overhead on these requests. Do the capabilities not come back on the device list request? Is it possible to include them on the device list request via some flag, if they are not returned by default?

2021-08-03 16:35 UTC, Mark-Powers commented
I see why I initially thought extra capabilities were not shown in the device list, but I see they were filtered out. This is updated.

2021-08-05 14:25 UTC, diurnalist approved these changes
Excellent!

2021-08-05 16:42 UTC, merged