Create button for node reallocation
ChameleonCloud/blazar-dashboard pull request #31
Opened 2022-07-15 19:51 UTC by super-cooper

Adds a button to the Lease Overview tab which allows the user to reallocate any of the hosts allocated to their lease. Also shows the "status" of each node: healthy/unhealthy, which maps to reservable/unreservable, or "unknown" if "reservable" is not set.

In order to embed the buttons in the Lease Overview tab, a patch to Horizon had to be made: https://github.com/ChameleonCloud/horizon/pull/18

The front-end changes were a little complicated. Some extra tag parameters needed to be added in order to get all of the dialogue functioning properly. Horizon would normally inject this information for you when buttons are defined as python classes, but in this case, that was not possible.

2022-07-15 19:51 UTC, super-cooper commented
![](https://github.trello.services/images/mini-trello-icon.png) [Dashboard - Create button for node reallocation](https://trello.com/c/f84M0dkQ/2706-dashboard-create-button-for-node-reallocation)

2022-07-15 19:56 UTC, super-cooper commented
This is probably something we should add to the docs now. Maybe right after [this section].(https://chameleoncloud.readthedocs.io/en/latest/technical/reservations.html#changing-the-number-of-nodes-of-a-lease)

2022-07-15 20:16 UTC, Mark-Powers requested changes
Reservable status should always be known, and so we should always have "healthy" or "unhealthy".

Also, after looking at this, I'm thinking we need to use a workflow instead. Is there a reason this isn't possible? That would also mean no horizon patch is needed.

2022-07-15 20:16 UTC, Mark-Powers commented on blazar_dashboard/content/leases/tabs.py
> +                node["reservable"] = "_"
Instead of this, you should update `nodes_in_lease` to include reservable: https://github.com/ChameleonCloud/blazar-dashboard/blob/chameleoncloud/xena/blazar_dashboard/api/client.py#L338-L342

It's a column on the node in the database, so it should always be set.

2022-07-15 20:41 UTC, super-cooper commented
> Also, after looking at this, I'm thinking we need to use a workflow instead. Is there a reason this isn't possible? That would also mean no horizon patch is needed.

It seemed much more complicated, but that was pretty early on in the development in this patch. I will take another look.

2022-07-15 21:26 UTC, super-cooper commented
I don't think workflow is the right move for this. It's only a single step, and workflows are supposed to be the little pop up windows which require 1 or more forms to be filled out and then submitted:

![image](https://user-images.githubusercontent.com/14908880/179313064-a55bfc0e-6d56-4827-85b0-5b81955c0352.png)


In this case, it's a single button that directly performs a single action. Are there any workflows in Horizon which function like this?

2022-07-15 21:38 UTC, Mark-Powers commented
> Are there any workflows in Horizon which function like this?

It looks like there is a [Form](https://opendev.org/openstack/blazar-dashboard/src/branch/master/blazar_dashboard/content/leases/forms.py#L32) that blazar dashboard uses upstream and it pops up a [modal](https://opendev.org/openstack/blazar-dashboard/src/branch/master/blazar_dashboard/content/leases/views.py#L85). It seems to [be the alternative to workflow](https://docs.openstack.org/horizon/latest/contributor/ref/forms.html#module-horizon.forms.views).

2022-07-28 21:11 UTC, super-cooper commented
This PR no longer depends on ChameleonCloud/horizon#18. The whole change should be able to go in as a Blazar dashboard patch.

2022-07-28 21:17 UTC, Mark-Powers approved these changes
Great work!

2022-07-28 21:26 UTC, merged